### ISSUE TITLE
INFOGRAFIA Kevin Cruz Hernádez

### ISSUE THREAD

**Issue by KevCH24** [SistemasTecTlaxiaco/infografia-de-hilos-KevCH24#2]
[Hilos en programacion Kevin Cruz Hernandez 4AS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-KevCH24/files/15044068/Hilos.en.programacion.Kevin.Cruz.Hernandez.4AS.pdf)

**Comment by Bryan080204** [comment]
18
 le falta mas informacion al igual que mas imagenes , el resto cumple con las rubricas correctamente

**Comment by josealfredo79** [comment]
Bien hecho..
